import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Providers from "@/components/Providers";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const amapKey = process.env.NEXT_PUBLIC_AMAP_KEY;
  const amapSecurityJsCode = process.env.NEXT_PUBLIC_AMAP_SECURITY_JS_CODE;
  return (
    <html lang="en">
      <body className={"antialiased"}>
        <NavBar />
        {amapSecurityJsCode && (
          <Script id="amap-security" strategy="beforeInteractive">
            {`window._AMapSecurityConfig = { securityJsCode: '${amapSecurityJsCode}' };`}
          </Script>
        )}
        {amapKey && (
          <Script
            src={`https://webapi.amap.com/maps?v=2.0&key=${amapKey}`}
            strategy="beforeInteractive"
          />
        )}
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
